import { Raleway } from "next/font/google";
import "./globals.css";
import ClientLayout from "../../components/ClientLayout";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


export const metadata = {
  title: "Ideal Interior",
  description: "Generated by create next app",
  icons: {
    icon: "https://ideal-interior-nepal.s3.ap-south-1.amazonaws.com/logos/logo-top-removebg-preview.png",
  },
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${raleway.variable} font-sans antialiased`}
      >
    <ClientLayout>
      {children}
    </ClientLayout>
      </body>
    </html>
  );
}

