"use client"
import { Raleway } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import { AppDataProvider } from "../../context/ContactInfoContext";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


// export const metadata = {
//   title: "Ideal Interior",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased`}
      >
    <QueryClientProvider client={queryClient}>
      <AppDataProvider>
        {children}
        </AppDataProvider>
    </QueryClientProvider>
      </body>
    </html>
  );
}

